version: "3"

services:
  production-doctranlate-fe:
    container_name: $CONTAINER_NAME
    image: $IMAGE_NAME
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
