# layer 1
FROM node:18-alpine as build_image
WORKDIR /app/react-app
COPY ./frontend/package.json .
RUN npm install
COPY ./frontend/. .
RUN npm run build

# layer 2
FROM node:18-alpine as production_image
WORKDIR /app/react-app
COPY --from=build_image /app/react-app/dist/ /app/react-app/dist/
COPY  ./frontend/.env .env
EXPOSE 3000

COPY ./frontend/package.json .
COPY ./frontend/vite.config.ts .
RUN npm install typescript
EXPOSE 3000

CMD ["npm","run","preview"]
